---
include:
  # 1. 親機：USBドングル（nRF52840の汎用ボード名を指定）
  - board: nrf52840dongle_nrf52840
    shield: glove43tb_dongle
    snippet: studio-rpc-usb-uart
    artifact-name: dongle

  # 2. 子機：右手（CENTRAL=n フラグで子機に降格）
  - board: seeeduino_xiao_ble
    shield: glove43tb_R rgbled_adapter
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: glove43tb_R

  # 3. 子機：左手（CENTRAL=n フラグで子機に降格）
  - board: seeeduino_xiao_ble
    shield: glove43tb_L rgbled_adapter
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: glove43tb_L

  # 4. 初期化用リセットファイル
  - board: seeeduino_xiao_ble
    shield: settings_reset
    artifact-name: settings_reset
